services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb-data:/data/db/
      - ./mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - '3000:3000'
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/web-app

volumes:
  mongodb-data:
  mongodb-log:
